# ------------ NAME ------------
name: <ADD_CONTAINER_PARENT_NAME_HERE>

# ------------ SERVICES ------------
services:
  # Database
  <ADD_PROJECT_NAME_HERE>-psql:
    image: postgres:13
    container_name: <ADD_PROJECT_NAME_HERE>-psql
    restart: on-failure
    ports:
      - ${DB_PG_PORT}
    networks:
      - <ADD_PROJECT_NAME_HERE>
    volumes:
      - amexio-<ADD_PROJECT_NAME_HERE>-admin-psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_USER: ${DB_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  # Elasticsearch
  <ADD_PROJECT_NAME_HERE>-elastic:
    image: elasticsearch:7.17.22
    container_name: <ADD_PROJECT_NAME_HERE>-elastic
    restart: on-failure
    ports:
      - ${ES_PORT}
    networks:
      - <ADD_PROJECT_NAME_HERE>
    volumes:
      - amexio-<ADD_PROJECT_NAME_HERE>-admin-elastic-data:/usr/share/elasticsearch/data
      - amexio-<ADD_PROJECT_NAME_HERE>-admin-elastic-logs:/usr/share/elasticsearch/logs
    environment:
      - TZ=${TZ}
      - node.name=${ES_NODE_NAME}
      - cluster.name=${ES_CLUSTER_NAME}
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ES_PWD}
      - LICENSE=basic
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test:
        ["CMD-SHELL", "sh -c 'curl -XGET http://localhost:9200/_cat/health'"]
      interval: 10s
      timeout: 5s
      retries: 3
  # Nuxeo
  <ADD_PROJECT_NAME_HERE>:
    image: ${NX_IMG}
    container_name: <ADD_PROJECT_NAME_HERE>
    restart: on-failure
    env_file: .env.exemple
    stdin_open: true
    tty: true
    depends_on:
      <ADD_PROJECT_NAME_HERE>-psql:
        condition: service_healthy
      <ADD_PROJECT_NAME_HERE>-elastic:
        condition: service_healthy
    ports:
      - ${NX_PORT}:8080
    networks:
      - <ADD_PROJECT_NAME_HERE>
    volumes:
      - amexio-<ADD_PROJECT_NAME_HERE>-admin-logs:/var/log/nuxeo
      - amexio-<ADD_PROJECT_NAME_HERE>-admin-data:/var/lib/nuxeo
      - amexio-<ADD_PROJECT_NAME_HERE>-admin-tmp:/tmp
      - ./nuxeo/conf.d:/etc/nuxeo/conf.d
      - ./nuxeo/bundles/to_install:/home/bundles
      - ./nuxeo/bundles/store:/opt/nuxeo/server/packages/store
    environment:
      # ------------ NUXEO ------------
      JAVA_OPTS: -XshowSettings:vm
      NUXEO_DEV: ${NX_DEV}
      NUXEO_CLID: ${NX_CLID}
      NUXEO_PACKAGES: ${NX_PACKAGES}

# ------------ NETWORKS ------------
networks:
  <ADD_PROJECT_NAME_HERE>:
    driver: bridge
    name: <ADD_PROJECT_NAME_HERE>
    external: true

# ------------ VOLUMES ------------
volumes:
  amexio-<ADD_PROJECT_NAME_HERE>-admin-psql-data:
  amexio-<ADD_PROJECT_NAME_HERE>-admin-elastic-data:
  amexio-<ADD_PROJECT_NAME_HERE>-admin-elastic-logs:
  amexio-<ADD_PROJECT_NAME_HERE>-admin-logs:
  amexio-<ADD_PROJECT_NAME_HERE>-admin-pid:
  amexio-<ADD_PROJECT_NAME_HERE>-admin-data:
  amexio-<ADD_PROJECT_NAME_HERE>-admin-tmp:
